uint32 handleMenu(uint32 choice, LinkedList* list);
void returnOrExit(LinkedList* list);
void addStudent(LinkedList *list);
void displayStudents(LinkedList *list);
void searchStudentsById(LinkedList* list);
void updateStudentById(LinkedList* list);
void deleteStudentById(LinkedList* list);
void calculateAverageGPA(LinkedList* list);
void findHighestGPA(LinkedList* list);
void findLowestGPA(LinkedList* list);
